"""M4 redemption receipts and coupon history"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_receipts",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["staff_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_id", "action", "request_id"),
    )
    op.add_column("coupons", sa.Column("claim_id", sa.Uuid(), nullable=True))
    op.execute("UPDATE coupons SET claim_id = id")
    op.alter_column("coupons", "claim_id", nullable=False)
    op.add_column("coupons", sa.Column("subject_id", sa.Uuid(), nullable=True))
    op.execute("UPDATE coupons SET subject_id = id")
    op.execute("""UPDATE coupons c SET subject_id = g.token FROM
        (SELECT event_id, member_id, min(id::text)::uuid AS token FROM coupons
         WHERE member_id IS NOT NULL GROUP BY event_id, member_id) g
        WHERE c.event_id = g.event_id AND c.member_id = g.member_id""")
    op.alter_column("coupons", "subject_id", nullable=False)
    op.add_column("coupons", sa.Column("replacement_of", sa.Uuid(), nullable=True))
    op.add_column("coupons", sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("coupons", sa.Column("redeemed_counter_id", sa.Uuid(), nullable=True))
    op.add_column("coupons", sa.Column("redeemed_by", sa.Uuid(), nullable=True))
    op.add_column("coupons", sa.Column("encrypted_reason", sa.LargeBinary(), nullable=True))
    op.drop_constraint(op.f("coupons_member_id_slot_id_key"), "coupons", type_="unique")
    op.create_index(
        "one_current_coupon",
        "coupons",
        ["member_id", "slot_id"],
        unique=True,
        postgresql_where=sa.text("status != 'VOID'"),
    )
    op.create_unique_constraint("coupons_replacement_of_key", "coupons", ["replacement_of"])
    op.create_foreign_key(
        "coupons_redeemed_counter_fkey", "coupons", "counters", ["redeemed_counter_id"], ["id"]
    )
    op.create_foreign_key(
        "coupons_redeemed_by_fkey", "coupons", "staff_users", ["redeemed_by"], ["id"]
    )
    op.create_foreign_key(
        "coupons_replacement_fkey", "coupons", "coupons", ["replacement_of"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().scalar(
        sa.text("SELECT count(*) FROM coupons WHERE replacement_of IS NOT NULL")
    ):
        raise RuntimeError(
            "Cannot downgrade coupon history; retain M4 or restore a reviewed backup"
        )
    op.drop_constraint("coupons_replacement_fkey", "coupons", type_="foreignkey")
    op.drop_constraint("coupons_redeemed_by_fkey", "coupons", type_="foreignkey")
    op.drop_constraint("coupons_redeemed_counter_fkey", "coupons", type_="foreignkey")
    op.drop_constraint("coupons_replacement_of_key", "coupons", type_="unique")
    op.drop_index(
        "one_current_coupon", table_name="coupons", postgresql_where=sa.text("status != 'VOID'")
    )
    op.create_unique_constraint(
        op.f("coupons_member_id_slot_id_key"),
        "coupons",
        ["member_id", "slot_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("coupons", "encrypted_reason")
    op.drop_column("coupons", "redeemed_by")
    op.drop_column("coupons", "redeemed_counter_id")
    op.drop_column("coupons", "redeemed_at")
    op.drop_column("coupons", "replacement_of")
    op.drop_column("coupons", "subject_id")
    op.drop_column("coupons", "claim_id")
    op.drop_table("operation_receipts")
    # ### end Alembic commands ###
